test_name = "Цикл for"

character_literal_as_u8 = "Указанные ниже литералы символов эквивалентны литералам своих значений в виде чисел"
current_array_elem = "текущий элемент массива"
current_index = "текущий индекс"
